name: ryadelsalehen
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter_launcher_icons: ^0.13.1
  syncfusion_flutter_pdfviewer: ^22.1.39

flutter_icons:
  android: true
  ios: true
  image_path: "images/1024.jpeg"


  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/elsaleheen1.pdf
    - images/elsalehen2.pdf
    - images/1024.jpeg
    - images/01 باب الإخلاص وإحضار النية- دليل المعاصرين.pdf
    - images/02 باب التوبة- دليل المعاصرين.pdf
    - images/03 باب الصبر- دليل المعاصرين.pdf
    - images/eng.lecture.pdf
    - images/00 مقدمة الإمام النووي- دليل المعاصرين.pdf
    - images/دليل المعاصرين_ الطبعة الرابعة_ تنسيق نهائي.pdf


